#!/usr/bin/env python3
"""Create the local review page for the verified Embeddings v15 candidate."""
from pathlib import Path
import html,json,subprocess,imageio_ffmpeg
import build_embeddings_v15 as b

def main():
 check=json.loads((b.OUT/'verification.json').read_text())
 assert check['output_sha256']==b.sha(b.DST)
 ff=imageio_ffmpeg.get_ffmpeg_exe()
 for name,start,duration in [('join-1',104,13),('join-2',161,10),('word-pieces',239.8,12)]:
  subprocess.run([ff,'-v','error','-y','-ss',str(start),'-i',str(b.DST),'-t',str(duration),'-vn','-ar','48000','-ac','1',str(b.OUT/(name+'.wav'))],check=True)
 jumps=[('Start',0),('Student ID',18.1),('Coffee first',70.72),('Add Coke',85.2),('Definitions',103.7),('Add Pepsi',118.6),('Citrus column',135.14),('Citrus values',139.8),('Taste test → AI',161.53),('Second audio join',175.4),('Inside the model',213),('Word pieces',252.7),('Close',264)]
 buttons=''.join(f'<button data-time="{b.output_frame(b.fr(t))/30:.3f}">{html.escape(label)}</button>' for label,t in jumps)
 guard=json.loads((b.OUT/'guard/transition-guard.json').read_text());assert guard['pass']
 audits=''.join(f'<li><a href="guard/{x["strip"]}">{x["frame"]/30:.2f}s · {html.escape(x["label"])}</a></li>' for x in guard['boundaries'])
 page='''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Embeddings v15 · Review</title>
<style>:root{color-scheme:light;--purple:#5436b8;--ink:#211a36}*{box-sizing:border-box}body{margin:0;background:#f6f4fa;color:var(--ink);font:16px/1.55 system-ui,sans-serif}main{max-width:1180px;margin:32px auto;padding:0 24px}h1{margin:0;font-size:34px;letter-spacing:-.7px}h2{font-size:21px}p{margin:10px 0 16px}.eyebrow{font-size:13px;letter-spacing:1.3px;text-transform:uppercase;color:var(--purple);font-weight:700}.lead{color:#655a75;margin-bottom:22px}.card{background:white;border:1px solid #e2dcea;border-radius:14px;padding:24px;margin:20px 0}video{display:block;width:100%;max-height:610px;background:#201c29;border-radius:10px}.jumps{display:flex;gap:8px;flex-wrap:wrap;margin-top:16px}button{font:inherit;font-size:14px;border:1px solid #d8cef0;border-radius:8px;padding:7px 11px;background:#f6f2ff;color:var(--purple);cursor:pointer}button:hover{background:#e9e0ff}button:focus-visible{outline:3px solid #8b6fde;outline-offset:2px}.columns{display:grid;grid-template-columns:1fr 1fr;gap:20px}.columns .card{margin:0}.note{font-size:14px;color:#6b607a}a{color:var(--purple)}audio{width:100%;margin:8px 0}.status{display:inline-block;padding:4px 9px;border-radius:5px;background:#ece6fa;color:var(--purple);font-size:12px;font-weight:700}summary{cursor:pointer;font-weight:650}.audit{columns:3;font-size:14px}footer{color:#72667f;font-size:13px;margin:26px 0}@media(max-width:760px){.columns{grid-template-columns:1fr}.audit{columns:1}main{padding:0 14px}.card{padding:16px}h1{font-size:28px}}</style></head><body><main>
<div class="eyebrow">Embeddings · v15</div><h1>Coffee first. Coke and Pepsi together.</h1><p class="lead">Built from uploaded version 2 · 4:21.8 · Review candidate</p>
<video id="video" controls preload="metadata" poster="captures/complete.png"><source src="../../Prompts/embeddings-v15.mp4" type="video/mp4">Your browser does not support this video.</video><nav class="jumps" aria-label="Jump to a moment">BUTTONS</nav>
<section class="card"><span class="status">BUILT FOR REVIEW</span><h2>What changed</h2><p>The table starts with headings, then reveals Coffee, Coke, and Pepsi in a fixed order. Coke and Pepsi remain adjacent. Citrus appears as an empty column before its three values arrive with the narration.</p><p>The vector, dimension, and value definitions use the lesson’s table. The student illustration has no banner; the comparison and model illustrations keep their complete labels. The word-piece example now has its own visual, and the course close remains through the last frame.</p><p>Two short narration cuts remove the “unique numerical fingerprint” claim and the overstrong reason for using thousands of dimensions. No new pauses or synthesized speech were added.</p><a href="../../Prompts/embeddings-v15.mp4" download>Download the candidate MP4</a></section>
<div class="columns"><section class="card"><h2>Listen to the two joins</h2><p class="note">These excerpts come from the encoded candidate. Numerical alignment checks pass; cadence has not been verified by direct listening.</p><strong>1:50.27 · Value → Pepsi</strong><audio controls preload="none" src="join-1.wav"></audio><strong>2:48.13 · Six/seven → thousands</strong><audio controls preload="none" src="join-2.wav"></audio></section>
<section class="card"><h2>Word-piece detail</h2><p>Version 2 explains that “unbelievable” splits into three tokens with separate rows. The visual shows <strong>un / belie / vable</strong>; the narration does not name each piece individually.</p><p>No unverified donor narration was added. If naming the pieces aloud is essential, this remains a focused narration decision.</p><audio controls preload="none" src="word-pieces.wav"></audio></section></div>
<section class="card"><h2>Checks completed</h2><p>All 7,854 frames decoded. 168 selected encoded frames matched their expected visuals. Audio alignment passed numerical checks across both joins and the remainder of the video. Automated checks passed at all 38 declared transitions.</p><p>Five-second contact sheets and the main scene-change strips were inspected, including the corrected table-to-AI transition and the literal final frame. No direct listening or continuous-motion review has been performed.</p><p class="note">The comparison board runs for about 47 seconds with five spoken comparisons and changing outlines. The model board runs for about 40 seconds with changing outlines. Both use complete views; no unrelated cutaways were inserted.</p><details><summary>Verification and frame evidence</summary><p><a href="verification.json">Encoded-file verification</a> · <a href="build.json">Build and source mapping</a> · <a href="guard/transition-guard.json">Transition results</a></p><p><a href="encoded-sheet-0.jpg">Frames 0–55s</a> · <a href="encoded-sheet-1.jpg">60–115s</a> · <a href="encoded-sheet-2.jpg">120–175s</a> · <a href="encoded-sheet-3.jpg">180–235s</a> · <a href="encoded-sheet-4.jpg">240s–end</a></p><ul class="audit">AUDITS</ul></details></section>
<footer>Review candidate only. The installed course video, lesson text, and uploaded source remain unchanged.</footer></main><script>const video=document.getElementById('video');document.querySelectorAll('[data-time]').forEach(button=>button.addEventListener('click',()=>{document.querySelectorAll('audio').forEach(a=>a.pause());video.currentTime=Number(button.dataset.time);video.play().catch(()=>{});}));document.querySelectorAll('audio').forEach(a=>a.addEventListener('play',()=>{video.pause();document.querySelectorAll('audio').forEach(other=>{if(other!==a)other.pause();});}));</script></body></html>'''
 (b.OUT/'review.html').write_text(page.replace('BUTTONS',buttons).replace('AUDITS',audits))
 print(b.OUT/'review.html')
if __name__=='__main__':main()
