#!/usr/bin/env python3
"""Build gemini-notebook/<slug>/ from Prompts/upload-sets.json.

For each lesson in the registry:
  gemini-notebook/<slug>/upload/      exactly the files to upload to Gemini Notebook, nothing else
  gemini-notebook/<slug>/PROMPT.txt   paste into the video customization box (never uploaded)
  gemini-notebook/<slug>/README.txt   what is in upload/, the save-as name, the post-only boards
  gemini-notebook/MANIFEST.json       source path + sha256 for every copied file

It also regenerates Prompts/<slug>-upload-files.txt from the same registry, so the
checklist and the folder can never disagree. The folder is derived and gitignored:
edit the registry or the sources, then run this again.

Usage:
  .video-venv/bin/python scripts/video/sync_gemini_notebook.py            # rebuild everything
  .video-venv/bin/python scripts/video/sync_gemini_notebook.py --lesson fake-trap
  .video-venv/bin/python scripts/video/sync_gemini_notebook.py --check    # report drift, change nothing
"""
from pathlib import Path
import argparse, hashlib, json, shutil, sys, datetime

ROOT = Path(__file__).resolve().parents[2]
REGISTRY = ROOT / "Prompts/upload-sets.json"
OUT = ROOT / "gemini-notebook"
WORDS = {1: "one", 2: "two", 3: "three", 4: "four", 5: "five", 6: "six", 7: "seven", 8: "eight", 9: "nine", 10: "ten"}


def sha(p: Path) -> str:
    return hashlib.sha256(p.read_bytes()).hexdigest()


def load():
    reg = json.loads(REGISTRY.read_text())
    lessons = reg["lessons"]
    slugs = [l["slug"] for l in lessons]
    dupes = {s for s in slugs if slugs.count(s) > 1}
    if dupes:
        sys.exit(f"duplicate slugs in registry: {sorted(dupes)}")
    return lessons


def sources(lesson):
    """Every file the folder is built from, in upload order, then the prompt."""
    files = [lesson["markdown"], *lesson["uploads"]]
    missing = [f for f in files + [lesson["prompt"]] if not (ROOT / f).is_file()]
    for p in lesson.get("post_only", []):
        if not (ROOT / p["asset"]).is_file():
            missing.append(p["asset"])
    if missing:
        sys.exit(f"{lesson['slug']}: missing source files: {missing}")
    names = [Path(f).name for f in files]
    if len(set(names)) != len(names):
        sys.exit(f"{lesson['slug']}: two uploads share a filename: {names}")
    return files


def checklist_text(lesson, files):
    n = len(files)
    lines = [
        f"{lesson['title'].upper()} — GEMINI NOTEBOOK UPLOAD CHECKLIST",
        f"GENERATED by scripts/video/sync_gemini_notebook.py from Prompts/upload-sets.json on {datetime.date.today().isoformat()}.",
        "Edit the registry, not this file. The same files sit ready in gemini-notebook/" + lesson["slug"] + "/upload/.",
        "",
        f"Upload these {WORDS.get(n, n)} files (they are the whole contents of gemini-notebook/{lesson['slug']}/upload/):",
    ]
    lines += [f"  {f}" for f in files]
    post = lesson.get("post_only", [])
    if post:
        lines += ["", "Do NOT upload (canonical page boards, inserted in the edit):"]
        for p in post:
            cover = f"; the upload variant {Path(p['covers']).name} stands in for it" if p.get("covers") else ""
            lines.append(f"  {p['asset']}  ({p['why']}{cover})")
    lines += [
        "",
        f"Paste {lesson['prompt']} into the customization box (gemini-notebook/{lesson['slug']}/PROMPT.txt is the same text).",
        "",
        "The Visible watermarking toggle does not take effect (verified 2026-09-20): every roll carries",
        "the corner mark and the build removes it (Edit Spec section 8). Leave it off; no action needed.",
        "",
        f"Save the raw roll as {lesson['save_as']}. If it already exists, use the next unused numbered",
        "filename (-reroll-2.mp4, -reroll-3.mp4, ...); never overwrite a raw roll or the live video.",
        "",
        "Do not upload this checklist, the prompt, README.txt, or any lesson PDF as a source.",
    ]
    if lesson.get("kit"):
        lines.append(f"Scene directions and status: {lesson['kit']}.")
    if lesson.get("notes"):
        lines += ["", f"Status: {lesson['notes']}"]
    return "\n".join(lines) + "\n"


def readme_text(lesson, files):
    n = len(files)
    lines = [
        f"{lesson['title']} — what to do",
        "",
        f"1. Upload every file in upload/ ({WORDS.get(n, n)} files). Nothing else goes in as a source.",
        "2. Paste PROMPT.txt into the video customization box.",
        f"3. Save the roll as {lesson['save_as']} (or the next unused -reroll-N name).",
        "",
        "upload/ contains:",
    ]
    lines += [f"  {Path(f).name}    <- {f}" for f in files]
    post = lesson.get("post_only", [])
    if post:
        lines += ["", "Not here on purpose (faces; the edit inserts them):"]
        lines += [f"  {p['asset']}" for p in post]
    lines += ["", "Generated by scripts/video/sync_gemini_notebook.py; run it again after any lesson or board change.",
              "The watermark toggle does not take effect; the build removes the mark."]
    if lesson.get("notes"):
        lines += ["", f"Status: {lesson['notes']}"]
    return "\n".join(lines) + "\n"


def build(lesson, manifest):
    files = sources(lesson)
    d = OUT / lesson["slug"]
    if d.exists():
        shutil.rmtree(d)
    (d / "upload").mkdir(parents=True)
    entries = []
    for f in files:
        src = ROOT / f
        dst = d / "upload" / src.name
        shutil.copy2(src, dst)
        entries.append({"upload": str(dst.relative_to(ROOT)), "source": f, "sha256": sha(src)})
    prompt = ROOT / lesson["prompt"]
    (d / "PROMPT.txt").write_text(prompt.read_text())
    (d / "README.txt").write_text(readme_text(lesson, files))
    (ROOT / "Prompts" / f"{lesson['slug']}-upload-files.txt").write_text(checklist_text(lesson, files))
    manifest[lesson["slug"]] = {
        "files": entries,
        "prompt": {"source": lesson["prompt"], "sha256": sha(prompt), "words": len(prompt.read_text().split())},
        "post_only": [p["asset"] for p in lesson.get("post_only", [])],
    }
    return len(files)


def check(lessons, only=None):
    mpath = OUT / "MANIFEST.json"
    if not mpath.exists():
        sys.exit("no gemini-notebook/MANIFEST.json yet; run without --check first")
    manifest = json.loads(mpath.read_text())["lessons"]
    drift = 0
    for lesson in lessons:
        if only and lesson["slug"] != only:
            continue
        m = manifest.get(lesson["slug"])
        if not m:
            print(f"{lesson['slug']}: not built yet"); drift += 1; continue
        want = [lesson["markdown"], *lesson["uploads"]]
        have = [e["source"] for e in m["files"]]
        if want != have:
            print(f"{lesson['slug']}: registry upload list changed"); drift += 1
        for e in m["files"]:
            src = ROOT / e["source"]
            if not src.is_file():
                print(f"{lesson['slug']}: source missing {e['source']}"); drift += 1
            elif sha(src) != e["sha256"]:
                print(f"{lesson['slug']}: STALE {e['source']} changed since sync"); drift += 1
            cp = ROOT / e["upload"]
            if not cp.is_file() or sha(cp) != e["sha256"]:
                print(f"{lesson['slug']}: copy missing or altered {e['upload']}"); drift += 1
        if sha(ROOT / lesson["prompt"]) != m["prompt"]["sha256"]:
            print(f"{lesson['slug']}: STALE prompt {lesson['prompt']} changed since sync"); drift += 1
    print("OK: gemini-notebook/ matches its sources" if not drift else f"{drift} problem(s); run the sync")
    return 1 if drift else 0


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--lesson", help="only this slug")
    ap.add_argument("--check", action="store_true", help="report drift; change nothing")
    a = ap.parse_args()
    lessons = load()
    if a.lesson and a.lesson not in {l["slug"] for l in lessons}:
        sys.exit(f"unknown lesson {a.lesson}; registry has: {[l['slug'] for l in lessons]}")
    if a.check:
        sys.exit(check(lessons, a.lesson))
    OUT.mkdir(exist_ok=True)
    mpath = OUT / "MANIFEST.json"
    manifest = json.loads(mpath.read_text())["lessons"] if mpath.exists() else {}
    for lesson in lessons:
        if a.lesson and lesson["slug"] != a.lesson:
            continue
        n = build(lesson, manifest)
        print(f"{lesson['slug']:24s} {n} uploads + PROMPT.txt  -> gemini-notebook/{lesson['slug']}/")
    mpath.write_text(json.dumps({"generated": datetime.datetime.now().isoformat(timespec="seconds"),
                                 "registry": "Prompts/upload-sets.json", "lessons": manifest}, indent=1))
    (OUT / "README.txt").write_text(
        "One folder per lesson. Open the lesson, upload everything in upload/, paste PROMPT.txt into the\n"
        "customization box, save the roll under the name in README.txt. This folder is generated from\n"
        "Prompts/upload-sets.json by scripts/video/sync_gemini_notebook.py and is not tracked in git;\n"
        "run the sync (or --check) before generating so the copies match lessons/ and course-assets/.\n")


if __name__ == "__main__":
    main()
