from pathlib import Path
import subprocess,json,sys,concurrent.futures,re
ROOT=Path(__file__).resolve().parents[2];sys.path.insert(0,str(ROOT/'scripts/video'))
from build_work_with_ai_illustration_pilot import OUT,FF,SOURCES
items=[('P1','art-of-prompting','Art of Prompting','Bring the actual draft','The student supplies a draft excerpt and an essay question, then asks what is unclear or generic. The paper beside the laptop uses the same fixing-cars example.'),('P2','context-window','Context Window','Make the file available','The assignment is initially only on the computer. A second state shows it shared in this chat. Two clear states fit the existing 4.5-second cutaway.'),('P3','evaluate-the-results','Evaluate the Results','Check what the source says','Both dates stay visible throughout. Emphasis moves from the AI answer to the school notice, making their disagreement easy to inspect. This uses the approved simpler comparison treatment.')]
def clip(job):
 pid,variant,src,start,duration=job;dest=OUT/f'clips/{pid}-{variant}.mp4'
 assert not dest.exists(),dest
 subprocess.run([FF,'-v','error','-ss',str(start),'-i',str(src),'-t',str(duration),'-c:v','libx264','-crf','18','-preset','veryfast','-c:a','aac','-b:a','128k','-movflags','+faststart',str(dest)],check=True)
jobs=[];sections=[]
def time(f):return f'{f//1800}:{(f/30)%60:05.2f}'
for pid,slug,title,heading,desc in items:
 cfg=SOURCES[slug];_,a,b=cfg['spans'][0]
 for variant,v in [('before',cfg['version']-1),('after',cfg['version'])]:jobs.append((pid,variant,ROOT/f'Prompts/{slug}-v{v}.mp4',a/30-3,(b-a)/30+6))
 sections.append(f'<section id="{pid}"><p class="eyebrow">{pid} · {title} · {time(a)}–{time(b)}</p><h2>{heading}</h2><p>{desc}</p><h3>Updated excerpt</h3><video controls playsinline preload="metadata" poster="previews/{pid}-state-1.jpg" src="clips/{pid}-after.mp4"></video><p class="caption">Includes three seconds of context before and after the insert. Player time is relative to the excerpt.</p><h3>Previous version</h3><video controls playsinline preload="metadata" src="clips/{pid}-before.mp4"></video><p><a href="../../Prompts/{slug}-v{cfg["version"]}.mp4">Full candidate · {title} v{cfg["version"]}</a> · <a href="{slug}-manifest.json">Edit record</a></p></section>')
with concurrent.futures.ThreadPoolExecutor(max_workers=2) as ex:list(ex.map(clip,jobs))
checks=json.loads((OUT/'verification.json').read_text())
qa=''.join(f'<li>{r["slug"]}: {r["frames"]:,} frames, {r["duration"]:.2f}s; complete decode and identical audio payload verified.</li>' for r in checks)
base=(ROOT/'video-audit/start-smarter-illustration-pilot-2026-10-07/review.html').read_text()
style=re.search(r'<style>(.*?)</style>',base,re.S).group(1)
html='''<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Work With AI — illustration pilot</title><style>'''+style+'''h3{font-size:17px;margin:24px 0 8px}</style><main><p class="eyebrow">Work With AI · Illustration pilot · 8 October 2026</p><h1>Show the practical steps.</h1><p class="intro">Three photographic inserts, using the natural student style from <em>Why Learn AI?</em> Screen text is rendered separately for clarity.</p><p>Approved and installed locally on 8 October 2026. Commit 4070c1c6; queued for batch deployment. Original narration, runtime, and board timing are preserved. <a href="local-install.json">Local release record</a>.</p><nav><a href="#P1">Bring the draft</a><a href="#P2">Share the file</a><a href="#P3">Check the source</a><a href="#checks">Checks & assets</a></nav>'''+''.join(sections)+f'''<section id="checks"><h2>Verification</h2><ul>{qa}</ul><p>Every changed frame was compared against its intended state. Unedited frames were sampled every second and at edit boundaries to check for unintended visual changes. All transition-guard checks passed; boundary strips and encoded screen states were inspected.</p><p>Source limitation: these narrow repairs start from the approved finished files and encode them once at CRF 16. Original audio is copied without reencoding in the full candidates. Preview excerpts use AAC audio for browser playback.</p><p>Review limit: continuous listening and audiovisual playback assessment have not been completed. Please listen to the three excerpts when judging timing and readability. This is a candidate review, not a full shipping certification.</p><p><a href="verification.json">Verification data</a> · <a href="REVIEW.md">Build record</a> · <a href="../work-with-ai-illustration-opportunities-2026-10-08/review.html">Approved proposal</a></p><h2>Photographic assets</h2><p>Created with the built-in image generation tool and saved in the project: <a href="assets/draft.png">draft scene</a>, <a href="assets/file.png">file scene</a>, <a href="assets/source.png">source scene</a>. <a href="assets/generation-record.json">Complete generation and edit prompts</a>.</p></section><footer>Exact existing cut boundaries: P1 1:54.90–2:04.33; P2 3:14.80–3:19.33; P3 2:50.20–2:55.90. All board openings, highlights, and camera treatments remain as in the source. No narration, pause, or timeline changes.</footer></main></html>'''
(OUT/'review.html').write_text(html)
missing=[p for p in re.findall(r'(?:src|href)="([^"#]+)"',html) if not (OUT/p).exists()]
assert not missing,missing
print(OUT/'review.html')
