from pathlib import Path
import subprocess,json,sys,concurrent.futures,re
ROOT=Path(__file__).resolve().parents[2];sys.path.insert(0,str(ROOT/'scripts/video'))
from build_understand_ai_illustration_updates import OUT,FF,SOURCES
items=[('P1','training','Training','Choose the more helpful answer','The learner compares two answers to the same basketball question. The actionable answer becomes selected in the training-feedback panel.'),('P2','embeddings','Embeddings','Give a characteristic a number','Students compare Coke and coffee and record a rating. The highlight follows each spoken dimension: Sweet 9, Bitter 1, Fizz 10, Heat 2, Caffeine 3, and Dark 8. Each score stays visible as the next one is introduced.'),('P3','ai-is-math','AI Is Math','One result known. One still unknown.','Both coin results start hidden. The first cover lifts to reveal heads; the second stays fully covered. The existing outcome-elimination diagram follows unchanged.')]
def clip(job):
 pid,variant,src,start,duration=job;dest=OUT/f'clips/{pid}-{variant}.mp4'
 if dest.exists():return
 subprocess.run([FF,'-v','error','-ss',str(start),'-i',str(src),'-t',str(duration),'-c:v','libx264','-crf','18','-preset','veryfast','-c:a','aac','-b:a','128k','-movflags','+faststart',str(dest)],check=True)
jobs=[];sections=[]
def time(f):return f'{f//1800}:{(f/30)%60:05.2f}'
for pid,slug,title,heading,desc in items:
 cfg=SOURCES[slug];_,a,b=cfg['spans'][0]
 for variant,v in [('before',cfg.get('source_version',cfg['version']-1)),('after-v12' if pid=='P2' else 'after',cfg['version'])]:jobs.append((pid,variant,ROOT/f'Prompts/{slug}-v{v}.mp4',a/30-3,(b-a)/30+6))
 after='after-v12' if pid=='P2' else 'after';poster=f'{pid}-v12-state-6.jpg' if pid=='P2' else f'{pid}-state-1.jpg'
 sections.append(f'<section id="{pid}"><p class="eyebrow">{title} · {time(a)}–{time(b)}</p><h2>{heading}</h2><p>{desc}</p><h3>Updated excerpt</h3><video controls playsinline preload="metadata" poster="previews/{poster}" src="clips/{pid}-{after}.mp4"></video><p class="caption">Includes three seconds of context before and after the insert. Player time is relative to the excerpt.</p><h3>Previous version</h3><video controls playsinline preload="metadata" src="clips/{pid}-before.mp4"></video><p><a href="../../Prompts/{slug}-v{cfg["version"]}.mp4">Full candidate · {title} v{cfg["version"]}</a> · <a href="{slug}-manifest.json">Edit record</a></p></section>')
with concurrent.futures.ThreadPoolExecutor(max_workers=2) as ex:list(ex.map(clip,jobs))
checks=json.loads((OUT/'verification.json').read_text())
qa=''.join(f'<li>{r["slug"]}: {r["frames"]:,} frames, {r["duration"]:.2f}s; complete decode and identical audio payload verified.</li>' for r in checks)
base=(ROOT/'video-audit/start-smarter-illustration-pilot-2026-10-07/review.html').read_text()
style=re.search(r'<style>(.*?)</style>',base,re.S).group(1)
html='''<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Understand AI — illustration updates</title><style>'''+style+'''h3{font-size:17px;margin:24px 0 8px}</style><main><p class="eyebrow">Understand AI · Illustration updates · 8 October 2026</p><h1>Make the learning action visible.</h1><p class="intro">Three photographic updates, using the natural student style from <em>Why Learn AI?</em> These continue the section-by-section improvements already established in Start Smarter and Work With AI.</p><p>Approved and shipped locally: Training v10, Embeddings v12, and AI Is Math v9. Commit 39d8d05e; queued for batch deployment. The installed videos preserve the original narration, runtime, course boards, and board timing. <a href="local-install.json">Local release record</a>.</p><nav><a href="#P1">Choose an answer</a><a href="#P2">Record a rating</a><a href="#P3">Reveal the coin</a><a href="#checks">Checks & assets</a></nav>'''+''.join(sections)+f'''<section id="checks"><h2>Verification</h2><ul>{qa}</ul><p>Every changed frame was compared against its intended state. Unedited frames were sampled every second and at edit boundaries to check for unintended visual changes. All fourteen current transition-boundary checks passed; boundary strips and encoded states were inspected.</p><p>Source limitation: these narrow updates start from the approved finished files and encode them once at CRF 16. Original audio is copied without reencoding in the full candidates. Preview excerpts use AAC audio for browser playback.</p><p>Continuous listening and audiovisual playback assessment by the agent have not been completed. The owner approved these versions for shipping after review. The checks above establish technical integrity; owner approval is recorded separately.</p><p><a href="verification.json">Verification data</a> · <a href="REVIEW.md">Build record</a> · <a href="../understand-ai-illustration-opportunities-2026-10-08/review.html">Approved proposal</a></p><h2>Photographic assets</h2><p>Created with the built-in image generation tool and saved in the project: <a href="assets/training.png">training-feedback scene</a>, <a href="assets/embeddings.png">drink-rating scene</a>, <a href="assets/coins-before.png">covered coins</a>, and <a href="assets/coins-after.png">first coin revealed</a>. Exact labels and interface text are rendered separately in the video build. <a href="assets/prompts.json">Complete generation and edit prompts</a>.</p></section><footer>Exact source cuts: Training 2:54.067–3:00.967; Embeddings 0:49.167–1:04.333; AI Is Math 1:43.300–1:49.867. All course-board openings, highlights, and camera treatments are retained. No narration, pause, or timeline changes.</footer></main></html>'''
(OUT/'review.html').write_text(html)
missing=[p for p in re.findall(r'(?:src|href)="([^"#]+)"',html) if not (OUT/p).exists()]
assert not missing,missing
print(OUT/'review.html')
