from pathlib import Path
import json,html,hashlib,re
OUT=Path(__file__).resolve().parent;ROOT=OUT.parent.parent
d=json.loads((OUT/'opportunities.json').read_text()); sources=json.loads((OUT/'sources.json').read_text())
e=html.escape
def stamp(t):return f'{int(t)//60}:{t%60:04.1f}' if t%1 else f'{int(t)//60}:{int(t)%60:02}'
def card(r):
 src=f'clips/{r["id"]}.mp4'
 return f'''<article id="{r['id']}" class="opportunity"><div class="cardtop"><span class="badge">{e(r['priority'])} · {r['id']}</span><span>{e(r['lesson'])} · {stamp(r['start'])}–{stamp(r['end'])}</span></div><h3>{e(r['title'])}</h3><div class="comparison"><div><figure><a href="{r['image']}"><img loading="lazy" src="{r['image']}" alt="Current video frame from {e(r['lesson'])} at {stamp(r['image_time'])}"></a><figcaption>Current frame · {stamp(r['image_time'])}</figcaption></figure><p><strong>What’s there:</strong> {e(r['current'])}</p><div class="clip"><h4>Current moment + context</h4><video controls playsinline preload="none" src="{src}" poster="{r['image']}" style="width:100%;margin-top:12px"></video><p class="small">Existing video excerpt, with up to three seconds of context on either side. Player time starts at the beginning of the excerpt.</p><a href="{src}">Open excerpt separately</a></div><p class="small"><a href="{r['sequence']}">Inspect frame sequence</a></p></div><div><h4>Proposed illustration</h4><p>{e(r['proposal'])}</p><ol class="beats">{''.join('<li>'+e(b)+'</li>' for b in r['beats'])}</ol><p><strong>Learning benefit:</strong> {e(r['benefit'])}</p><p class="criterion"><strong>Keep it only if:</strong> {e(r['success'])}</p></div></div><details><summary>Narration and proposed treatment</summary><blockquote>{e(r['cue'])}</blockquote><p>{e(r['treatment'])}</p><p><strong>Course boards:</strong> {e(r['board'])}</p></details></article>'''

style=re.search(r'<style>(.*?)</style>',(OUT.parent/'understand-ai-illustration-opportunities-2026-10-08/review.html').read_text(),re.S).group(1)
rows=''.join(f'<tr><td>{e(r["title"])}</td><td>{e(r["decision"])}</td><td>{e(r["reason"])}</td></tr>' for r in d['lessons'])
evidence=[]
for r in sources:
 slug=r['slug']; sheets=sorted((OUT/slug).glob('sheet-*.jpg'))
 links=' · '.join(f'<a href="{p.relative_to(OUT)}">Sheet {i+1}</a>' for i,p in enumerate(sheets))
 evidence.append(f'<li><strong>{e(next(x["title"] for x in d["lessons"] if x["slug"]==slug))}</strong> · {stamp(r["duration"])}<br>{links} · <a href="transcripts/{slug}.txt">Transcript</a> · <a href="{slug}/source.json">Source record</a></li>')
text=f'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Build Your Skills — Illustration Opportunities</title><style>{style}</style></head><body><main><header><div class="eyebrow">Illustration updates · October 8, 2026</div><h1>Build Your Skills: put the skills into action.</h1><p>{e(d['recommendation'])}</p><div class="note">The next section in the established illustration improvement pass. Each proposal below includes the <strong>current video excerpt</strong>, the teaching benefit, and a concrete scene plan. Proposed images have not yet been generated.</div><nav aria-label="Report sections"><a href="#updates">Three proposed updates</a><a href="#coverage">All nine videos</a><a href="#production">Build approach</a><a href="#evidence">Evidence & scope</a></nav></header>
<section class="reference"><figure><img src="../start-smarter-illustration-opportunities-2026-10-07/why-learn-ai/detail/170.jpg" alt="Style reference: student revising a garden project with feedback"><figcaption>Style reference · Why Learn AI? · 2:50</figcaption></figure><div><div class="eyebrow">Carry forward the established style</div><h3>A person, a specific action, visible work.</h3><p>Believable students, natural light, ordinary clothing, and realistic school or home settings. Precise text and interface controls are rendered separately so they remain readable.</p><p>The illustration earns its place by making the action clearer. Existing diagrams, course boards, and useful animation remain.</p></div></section>
<section id="updates"><h2>Three moments worth improving</h2><p>These are small replacements inside existing supporting shots. All nine videos have been checked for opportunities; four are keep-current decisions, the opener awaits narration work, and Know the App is now in production.</p>{''.join(card(r) for r in d['opportunities'])}</section>
<section id="coverage"><h2>Decision for every video</h2><table><thead><tr><th>Lesson</th><th>Decision</th><th>Reason and visuals to preserve</th></tr></thead><tbody>{rows}</tbody></table></section>
<section id="production"><h2>Build approach</h2><p>Use the exact current video sources recorded below. Preserve narration, duration, board wording, board highlights, camera moves, and closing frames. The three proposed intervals total <strong>{sum(r['end']-r['start'] for r in d['opportunities']):.2f} seconds</strong>. Frame-difference checks located the existing shot boundaries; inspect those frames again before final compositing.</p><p>P1 follows one group through interruption and withdrawal. P2 keeps a coherent court layout while separating exploration from changing the play. P3 uses one clear scene of students following through. Use multiple states where the narration changes the situation; avoid long static holds.</p><p>Generate only the photographic settings and people. Composite exact words, highlights, and court routes separately. Produce before/after excerpts with existing narration, then verify the final encoded states and joins. The finished source files are available; if pristine assemblies cannot be reused, disclose the additional video encode and copy the original audio without reencoding.</p><details><summary>Corrected status: Know the App</summary><p>The installed file still contains the old Your Choices lesson. However, the renamed and revised Know the App lesson already has current prep materials and a newer roll 6 that passed narration review on October 1. The owner authorized production on October 8. My initial audit missed that newer review. <a href="../know-the-app-2026-10-01/REVIEW-4-6.md">Current narration review</a> · <a href="../know-the-app-2026-10-01/EDIT-PLAN.md">Production plan</a>.</p><p>The section opener remains deferred pending its previously recorded narration work. The three illustration proposals preserve current narration and owner-approved exceptions.</p></details></section>
<section id="evidence"><h2>Evidence and scope</h2><p>{e(d['scope'])}</p><p>{e(d['method'])}</p><p>All source hashes were rechecked after preparation. Continuous playback with audible narration has not been performed, so timing proposals still need an encoded excerpt review with sound. The Video Tracker was not accessed or edited. No videos, canonical boards, or site files were changed by this audit.</p><ul class="evidence">{''.join(evidence)}</ul><p><a href="opportunities.json">Structured proposal</a> · <a href="sources.json">Source hashes</a> · <a href="review-checks.json">Review checks</a> · <a href="lesson-context.txt">Current page context</a> · <a href="../../scripts/video/EDIT-SPEC.md">Edit standards</a></p></section><footer>Illustration proposals for review. This is not a new narration verdict or shipping certification.</footer></main><script>document.querySelectorAll('video').forEach(v=>v.addEventListener('play',()=>document.querySelectorAll('video').forEach(other=>{{if(other!==v)other.pause()}})))</script></body></html>'''
(OUT/'review.html').write_text(text)
for r in sources:assert hashlib.sha256(Path(r['source']).read_bytes()).hexdigest()==r['sha256'],r['slug']
checks=dict(local_links_resolve=True,video_hashes_unchanged=True,videos=len(sources),total_duration_seconds=sum(r['duration'] for r in sources),full_decode_counts_match=all(r['frames']==r['decoded_frames'] for r in sources),continuous_audiovisual_review=False,visually_reviewed_contact_sheets=20,visually_reviewed_detail_sequences=3,proposed_updates=len(d['opportunities']),proposed_insert_seconds=round(sum(r['end']-r['start'] for r in d['opportunities']),2),source_boundary_frames={'people-skills':[0,798],'curious-and-flexible':[0,911],'make-your-move':[8167,8343]})
(OUT/'review-checks.json').write_text(json.dumps(checks,indent=2)+'\n')
missing=[p for p in re.findall(r'(?:src|href)="([^"#]+)"',text) if not (OUT/p.split('#')[0]).exists()]
assert not missing,missing
print(json.dumps(checks))
