from pathlib import Path
import json,subprocess,concurrent.futures,re
import imageio_ffmpeg
OUT=Path(__file__).resolve().parent;ROOT=OUT.parent.parent
rows=[dict(id='P1',priority='Recommended update',slug='document-trap',lesson='Document Trap',title='Show the learner checking the quotation',start=5525/30,end=5930/30,image='document-trap/detail/190.jpg',image_time=190,sequence='document-trap/detail/sequence-179.jpg',cue='A quotation is useful because you can check it, not because AI quoted it.',current='A small process diagram routes a pasted tournament passage into an AI context window and displays “Verification Status: Confirmed.” The matching text is present, but the learner’s act of checking is missing.',proposal='A photographic student at a table with the original rulebook open beside the AI quotation. Put two readable excerpts beside the photograph: “Original rulebook · Tournament” and “AI quotation.” Guide attention to the same six-foul exception in both. Show the student comparing the words before the match is emphasized.',benefit='Makes verification something the learner does with the original document. It gives the final quotation-checking line a concrete action, rather than letting an AI status badge stand in for checking.',beats=['Locate the tournament passage in the original.','Compare the quotation against that passage.','Emphasize the matching exception only after the comparison.'],treatment='13.50 seconds within the existing supporting shot. Label the rulebook “Lesson example”; the six-foul rule belongs to this scenario, not every basketball league. Use short, identical excerpt wording such as “Tournament games: six personal fouls.” Render all text separately and preserve context labels. No invented league, section number, citation, or automatic verified stamp. The inherited spoken “force the system” overclaim is not repaired by this visual; the earlier narration-repair note remains applicable.',board='Preserve An Incomplete Answer, Split/Search/Load, all four retrieval-move cards, their cameras and rings, and the complete close. Start after the Ask for the Quote card exits. Continue the comparison through the final quotation-checking line, preserving the owner-approved removal of the brief board return.',success='The learner can point to the original passage and explain how they checked the quotation, without treating AI’s own confidence as verification.'),
dict(id='P2',priority='Recommended update',slug='support-trap',lesson='Support Trap',title='Make the step outside the chat visible',start=3506/30,end=3886/30,image='support-trap/detail/124.jpg',image_time=124,sequence='support-trap/detail/sequence-115.jpg',cue='The AI builds the plan, but you still have to send the email, speak to your parents, or sit down and start studying.',current='A three-column process diagram highlights Preparation, with a tiny calendar and a study-plan label. It explains the category, but the examples remain abstract.',proposal='Use a stable three-panel photographic scene: a student with a teacher-email draft, a student preparing to talk with a parent, and a student with a study plan and open work. As the narration shifts to action, highlight Send, Talk, and Start in order. Show the email being sent, the parent conversation underway, and the first study problem begun.',benefit='Connects AI preparation to an observable next step. The student can see what still has to happen after the chat has helped.',beats=['Establish the three prepared tasks: email, conversation, study plan.','Shift emphasis to “You take the next step.”','Highlight Send → Talk → Start as each action is spoken.'],treatment='12.67 seconds. Three clean panels stay in fixed positions; use short labels and simple paired states, not three busy animated stories. The opening narration finishes the parents/study examples; focus those panels as named. Reveal the later action states only on the spoken Send/Talk/Start cues. Use ordinary schoolwork situations and natural expressions. No new crisis scenario or staged depiction of the real person discussed later. Keep the final state readable until the existing Danger board returns.',board='Preserve the complete three-jobs board, its ordinary-venting and danger explanations, the existing photographic cafeteria insert, the content note, the later story, all safety guidance, and the standard close. Replace only the supporting Preparation diagram between its existing cuts.',success='The learner distinguishes an AI-prepared draft or plan from sending, talking, or doing the work. Each action must be clear at normal playback speed.'),
dict(id='P3',priority='Recommended update',slug='fake-trap',lesson='Fake Trap',title='Show the saved-contact callback',start=6068/30,end=6217/30,image='fake-trap/detail/205.jpg',image_time=205,sequence='fake-trap/detail/sequence-193.jpg',cue='If a voicemail asks for something urgent, call back on the number you already have saved for them.',current='A cassette icon marked Urgent Request sits beside an address-book icon. The diagram describes a trusted callback, but uses symbols instead of showing the phone action.',proposal='A close photographic view of a student’s hand and phone, with a large readable interface composited alongside it. Move from the urgent voicemail to a previously saved contact such as Mom, then initiate a new call from that contact. Make “Saved contact” the dominant label.',benefit='Turns “verify somewhere the sender does not control” into a specific, repeatable action: choose a known contact rather than returning the incoming message’s number.',beats=['Leave the incoming voicemail.','Open the contact already saved on the phone and place a new call.'],treatment='4.97 seconds: the shortest insert, so use one fixed close-up, two clear states, and almost no reading. Avoid legible phone numbers, new spoken dialogue, a fake caller-ID reveal, or a confirmation that the request was genuine. The visible result is “Calling Mom,” not “Verified.” Confirm that both states read comfortably in the encoded excerpt; simplify the interface if necessary.',board='Keep the source/context/corroboration board, the repost distinction, the preceding independent-source diagram, and the following viral-clip source example. Preserve the shortened sequence approved in v10; do not reintroduce the deleted school-closure walkthrough. Later reporting and support guidance remains intact.',success='The learner recognizes a fresh call from an existing saved contact, rather than tapping Call Back on the suspicious voicemail.')]
lessons=[
('avoid-traps-opener','Avoid Traps — Opener','Keep current','The rip-current diagram, photographic Read the Water board, grammatical-but-false sentence, and section map already make hidden risk visible. The relaxed-user cutaway could be restyled, but a new photograph would add little teaching.'),
('hallucination','Hallucination','Keep current','Preserve the recently rebuilt credibility details, next-token example, original-source comparison, and shortened Stanford/pizza applications. They already show the checking process; a student photograph would hide useful evidence.'),
('training-bias','Training Bias','Keep current','The cows/background contrast, defaults/blind-spots/wrong-patterns cards, sameness comparison, and context-versus-weights sequence explain the mechanisms. Keep the photographic cow-testing board and the approved tighter RAG transition.'),
('document-trap','Document Trap','Update P1 only','Make the learner’s comparison with the original visible. Preserve retrieval mechanics, board cameras, rulebook setup, and the final quotation line. Previously recorded narration overclaims remain outside this visual proposal.'),
('mind-trap','Mind Trap','Keep current','The mother/chatbot comparison, readable ELIZA exchange, stakes progression, and preparation-versus-decision diagram carry the distinction. A new college-planning scene would repeat the photographic comparison already in the lesson.'),
('flattery-trap','Flattery Trap','Keep current','The Gatsby comparison already names the missing thesis and a next step. Keep its enlarged cards, ranking explanation, five prompt moves, and rubric/work alignment. A new photo in the short rubric cutaway would offer less time to read the evidence.'),
('engagement-trap','Engagement Trap','Keep current','The follow-up choices, 25-minute detour timer, autoplay/streak examples, and pause prompt already make the missing decision point concrete. Preserve the owner-requested first-board zoom/pan and existing stopping-point illustrations.'),
('support-trap','Support Trap','Update P2 only','Make preparation turn into action. Keep the strong cafeteria photograph, three-jobs distinction, warning, real-person story, and safety sequence. The proposed scene uses only ordinary preparation examples.'),
('fake-trap','Fake Trap','Update P3 only','Make the trusted callback visible. Keep the principal-clip comparison, detector limitations, independent-confirmation diagrams, context-date example, and reporting guidance. Do not restore material removed in v10.')]
sources=json.loads((OUT/'sources.json').read_text());total=sum(r['duration'] for r in sources)
d=dict(date='2026-10-08',scope=f'All nine current standard Avoid Traps videos, {int(total)//60} minutes {round(total%60)} seconds in total. Source selection follows the current local LESSON_VIDEOS entries.',method='Decoded all nine source videos sequentially and matched their reported frame counts. Visually inspected all 23 contact sheets sampled every six seconds, plus five one-second detail sequences. Read fresh full-file timestamped transcripts for all nine, current lesson material and relevant retained repair records. This is a frame-and-transcript illustration audit, not continuous audiovisual viewing, a new narration verdict, or a fact-check of every inherited claim. Automated transcript wording can contain recognition errors.',recommendation='Build three targeted illustration updates: check the original quotation, act on AI preparation, and call a saved contact. About 31 seconds of supporting imagery across three videos; keep the other six videos unchanged.',opportunities=rows,lessons=[dict(slug=s,title=t,decision=d,reason=r) for s,t,d,r in lessons])
(OUT/'opportunities.json').write_text(json.dumps(d,indent=2,ensure_ascii=False)+'\n')
# Preserve only relevant excerpts of the current lesson authority as audit evidence.
page=(ROOT/'index.html').read_text().splitlines();blocks=[]
for a,b in [(1224,1264),(6260,6400),(8040,8111),(8900,9035),(9214,9260),(10814,10909),(10923,11068),(11380,11443),(11485,11536)]:
 blocks.append(f'\n--- index.html lines {a}-{b} ---\n'+'\n'.join(page[a-1:b]))
(OUT/'lesson-context.txt').write_text('\n'.join(blocks))
(OUT/'clips').mkdir(exist_ok=True);ff=imageio_ffmpeg.get_ffmpeg_exe()
def clip(r):
 p=OUT/'clips'/f'{r["id"]}.mp4'
 if p.exists():return
 subprocess.run([ff,'-v','error','-ss',str(r['start']-3),'-i',str(ROOT/'course-assets'/r['slug']/(r['slug']+'.mp4')),'-t',str(r['end']-r['start']+6),'-vf','scale=960:540','-c:v','libx264','-preset','veryfast','-crf','20','-c:a','aac','-b:a','128k','-movflags','+faststart',str(p)],check=True)
with concurrent.futures.ThreadPoolExecutor(max_workers=3) as ex:list(ex.map(clip,rows))
print('Prepared three proposals and current-source excerpts')
