from pathlib import Path
import json, html, hashlib, re
OUT=Path(__file__).resolve().parent; ROOT=OUT.parent.parent
d=json.loads((OUT/'opportunities.json').read_text());sources=json.loads((OUT/'sources.json').read_text())
e=html.escape
def stamp(t):return f'{int(t)//60}:{t%60:05.2f}'
def card(r):
 return f'''<article id="{r['id']}" class="opportunity"><div class="cardtop"><span class="badge">{r['id']} · Recommended update</span><span>{e(r['lesson'])} · {stamp(r['start'])}–{stamp(r['end'])}</span></div><h3>{e(r['title'])}</h3><div class="comparison"><div><figure><a href="{r['image']}"><img loading="lazy" src="{r['image']}" alt="Current {e(r['lesson'])} frame at {stamp(r['image_time'])}"></a><figcaption>Current frame · {stamp(r['image_time'])}</figcaption></figure><p><strong>What’s there:</strong> {e(r['current'])}</p><div class="clip"><h4>Current moment + context</h4><video controls playsinline preload="none" src="clips/{r['id']}.mp4" poster="{r['image']}" style="width:100%;margin-top:12px" aria-label="{e(r['lesson'])} current excerpt"></video><p class="small">Current installed video, including three seconds before and after the proposed span. Player time starts at the beginning of the excerpt.</p><a href="clips/{r['id']}.mp4">Open excerpt separately</a></div><p class="small"><a href="{r['sequence']}">Inspect frame sequence</a></p></div><div><h4>Proposed illustration</h4><p>{e(r['proposal'])}</p><ol class="beats">{''.join('<li>'+e(b)+'</li>' for b in r['beats'])}</ol><p><strong>Learning benefit:</strong> {e(r['benefit'])}</p><p class="criterion"><strong>Keep it only if:</strong> {e(r['success'])}</p><p class="small"><strong>Style reference:</strong> {e(r['reference'])}</p></div></div><details><summary>Narration and production boundaries</summary><blockquote>{e(r['cue'])}</blockquote><p>{e(r['treatment'])}</p><p><strong>Boards and timing:</strong> {e(r['board'])}</p><p class="small">Exact replacement interval: frames [{r['start_frame']}, {r['end_frame_exclusive']}) at 30 fps.</p></details></article>'''
style=re.search(r'<style>(.*?)</style>',(OUT.parent/'understand-ai-illustration-opportunities-2026-10-08/review.html').read_text(),re.S).group(1)
style+='\n.beats{display:block;padding:18px 18px 18px 36px}.beats li{margin:0 0 12px}.beats li:last-child{margin-bottom:0}'
rows=''.join(f'<tr><td>{e(r["title"])}</td><td>{e(r["decision"])}</td><td>{e(r["reason"])}</td></tr>' for r in d['lessons'])
evidence=[]
for r in sources:
 slug=r['slug'];sheets=sorted((OUT/slug).glob('sheet-*.jpg'))
 links=' · '.join(f'<a href="{p.relative_to(OUT)}">Sheet {i+1}</a>' for i,p in enumerate(sheets))
 evidence.append(f'<li><strong>{e(next(x["title"] for x in d["lessons"] if x["slug"]==slug))}</strong> · {stamp(r["duration"])}<br>{links} · <a href="transcripts/{slug}.txt">Transcript</a> · <a href="{slug}/source.json">Source record</a></li>')
total_insert=sum(r['end']-r['start'] for r in d['opportunities'])
text=f'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Embrace the Future — Learning Illustration Pass</title><style>{style}</style></head><body><main><header><div class="eyebrow">Learning Illustration Pass · October 8, 2026</div><h1>Embrace the Future: make the responsibility tangible.</h1><p>{e(d['recommendation'])}</p><div class="note"><strong>Nine videos reviewed. Three targeted proposals.</strong> Current excerpts and exact scene plans are below. Proposed images have not yet been generated.</div><nav aria-label="Report sections"><a href="#updates">Three proposed updates</a><a href="#coverage">All nine videos</a><a href="#production">Build approach</a><a href="#evidence">Evidence & scope</a></nav></header>
<section class="reference"><figure><img src="../start-smarter-illustration-opportunities-2026-10-07/why-learn-ai/detail/170.jpg" alt="Approved Why Learn AI reference showing a student revising a garden project"><figcaption>Approved reference · Why Learn AI? · 2:50</figcaption></figure><div><div class="eyebrow">Preserve the established style</div><h3>A specific action, at the moment it is taught.</h3><p>Believable students and settings, visible work, precise screen content and restrained motion. Matched states show what changes as the narration explains it.</p><p>Useful existing drawings remain—including the map analogy and the unexpected-results stories. <a href="../../scripts/video/LEARNING-ILLUSTRATION-PASS.md">Read the documented process</a>.</p></div></section>
<section id="updates"><h2>Three moments worth improving</h2><p>Each proposal replaces one existing supporting shot. Together: <strong>{total_insert:.2f} seconds</strong> out of 37 minutes 33 seconds. The rest of the section already has effective visual teaching or recent targeted repairs.</p>{''.join(card(r) for r in d['opportunities'])}</section>
<section id="coverage"><h2>Decision for every video</h2><table><thead><tr><th>Lesson</th><th>Decision</th><th>Reason and visuals to preserve</th></tr></thead><tbody>{rows}</tbody></table></section>
<section id="production"><h2>Build approach</h2><p>Keep narration, runtime, frame rate, all canonical boards, existing board highlights, camera moves and closing frames. Match the current shot boundaries. No narration cuts, new pauses, or unusual board framing are proposed.</p><p>P1 and P3 use two matched photographic states with separately rendered instructional details. P2 uses one clear facility view for its four-second interval. Inspect relevant approved reference frames before generating each scene, and save prompts, assets, timing and source provenance with the build.</p><p>Build a fresh candidate for each selected video, with before/after excerpts and a full review copy. Verify encoded imagery, transitions, frame count and audio identity. Reuse pristine assemblies where available; if only the finished video survives, record the additional encoding required and preserve its audio.</p><p>The current plan preserves later repairs: Loudest Voices v8, Pace of Change v10, Big Downside v6, Big Upside v7, Rise of Agents v7, Work Changes v5, Data Centers v5 and Unexpected Results v3. Older flags do not override these installed versions.</p></section>
<section id="evidence"><h2>Evidence and scope</h2><p>{e(d['scope'])}</p><p>{e(d['method'])}</p><p>Source hashes were rechecked after preparation. Current excerpt playback is checked separately from a full listening pass; continuous audible review has not been performed. The Video Tracker was not accessed or edited. This audit has not changed any course video, board, lesson or site file.</p><ul class="evidence">{''.join(evidence)}</ul><p><a href="REVIEW.md">Review record</a> · <a href="opportunities.json">Structured proposals</a> · <a href="sources.json">Source hashes</a> · <a href="review-checks.json">Review checks</a> · <a href="../../scripts/video/EDIT-SPEC.md">Edit standards</a></p></section><footer>Illustration opportunities for review. Proposed scenes are not built or shipped.</footer></main></body></html>'''
(OUT/'review.html').write_text(text)
md='# Embrace the Future — Learning Illustration Pass\n\n2026-10-08. Status: opportunities prepared for review; no candidate builds or installation.\n\n'+d['recommendation']+'\n\n## Review method\n\n'+d['scope']+'\n\n'+d['method']+'\n\nThe Video Tracker was not accessed. No continuous audible review or new factual certification is claimed. ASR renderings of names and “worrier” are not new narration flags. Loudest Voices’ earlier pronunciation flag was explicitly resolved by the owner, and v8 framing/label repairs are installed.\n\n## Proposed replacements\n'
for r in d['opportunities']:
 md+=f'\n### {r["id"]}: {r["lesson"]} — {r["title"]}\n\n- Span: {stamp(r["start"])}–{stamp(r["end"])}; frames [{r["start_frame"]}, {r["end_frame_exclusive"]}) at 30 fps.\n- Narration: {r["cue"]}\n- Current: {r["current"]}\n- Proposal: {r["proposal"]}\n- Benefit: {r["benefit"]}\n- Treatment: {r["treatment"]}\n- Preserve: {r["board"]}\n- Reference: {r["reference"]}\n- Acceptance: {r["success"]}\n'
md+='\n## Section coverage\n\n'
for r in d['lessons']:md+=f'- **{r["title"]}: {r["decision"]}.** {r["reason"]}\n'
md+='\n## Next build constraints\n\nPreserve all narration, runtime, FPS, canonical boards and highlights, camera paths and close frames. No new pauses or board framing. Keep exact exclusive frame ends. Generate scenes only after plan approval, retaining prompts and matched-state provenance. Produce new versioned candidates and before/after excerpts. Verify decoded frame counts, copied audio, encoded states and entry/exit joins. No shipping authority is inferred from this opportunities review.\n\nSee `review.html`, `opportunities.json`, `sources.json` and `review-checks.json` for the review and evidence.\n'
(OUT/'REVIEW.md').write_text(md)
for r in sources:assert hashlib.sha256(Path(r['source']).read_bytes()).hexdigest()==r['sha256'],r['slug']
missing=[p for p in re.findall(r'(?:src|href)="([^"#]+)"',text) if p!='review-checks.json' and not (OUT/p.split('#')[0]).exists()]
assert not missing,missing
checks=dict(local_links_resolve=True,video_hashes_unchanged=True,videos=len(sources),total_duration_seconds=sum(r['duration'] for r in sources),full_decode_counts_match=all(r['frames']==r['decoded_frames'] for r in sources),continuous_audiovisual_review=False,visually_reviewed_contact_sheets=22,visually_reviewed_detail_sequences=5,proposed_updates=3,proposed_insert_seconds=round(total_insert,3),source_boundary_frames={r['slug']:[r['start_frame'],r['end_frame_exclusive']] for r in d['opportunities']},browser_playback_checked=False)
(OUT/'review-checks.json').write_text(json.dumps(checks,indent=2)+'\n')
print(json.dumps(checks))
